// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTpqO0edTRUtMHwLR-En5drF7Mg5FAPVQ',
    appId: '1:1046481105000:web:f0fbfb65493d8117f90bdd',
    messagingSenderId: '1046481105000',
    projectId: 'jobmoim-ec789',
    authDomain: 'jobmoim-ec789.firebaseapp.com',
    storageBucket: 'jobmoim-ec789.firebasestorage.app',
    measurementId: 'G-33MB0JTVY9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI6XVJw_cIc1zhHrMGqPtXUf97i-t-IiA',
    appId: '1:1046481105000:android:3036062cf45c8222f90bdd',
    messagingSenderId: '1046481105000',
    projectId: 'jobmoim-ec789',
    storageBucket: 'jobmoim-ec789.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRpg-mV3IrRLQtayWPO8fMIv2Ggdmg3OQ',
    appId: '1:1046481105000:ios:03c222d0e3368a06f90bdd',
    messagingSenderId: '1046481105000',
    projectId: 'jobmoim-ec789',
    storageBucket: 'jobmoim-ec789.firebasestorage.app',
    iosBundleId: 'com.example.jobmoim',
  );

}